# Server configuration
server:
  port: :1111
  mode: debug

# Database configuration
database:
  host: 127.0.0.1
  port: 3306
  name: newapp
  username: root
  password: Fracture@123

# Logging configuration
logging:
  level: debug
  file: log.log

# JWT configuration
jwt:
  secret: your-secret-key
  expiration: 3600 # in seconds
